package com.fairydoo.game.art

/**
 * Flora, die Waldfee — die Vorlage für alle übrigen.
 *
 * Große Monarchenfalter-Flügel in Orange und Gelb, grünes Blätterkleid, braunes
 * Haar mit Fühlern. Ihre Silhouette (Fühler, Kopf, schmaler Leib, zwei
 * Flügelpaare, Beine) ist die gemeinsame Grundform des ganzen Sets: Die anderen
 * neun Feen ändern Farben, Flügelform und ihr Kennzeichen, behalten aber diesen
 * Aufbau — nur so wirken zehn eigenständige Charaktere als eine Familie.
 *
 *      Spalten  0         1         2         3
 *               0123456789012345678901234567890 1
 */
val FloraSprite = PixelSprite(
    palette = fairyPalette(
        'h' to 0xFF9C6B42.toInt(), // Haar hell
        'H' to 0xFF6B4428.toInt(), // Haar Schatten, Fühler
        'g' to 0xFF7DFF9E.toInt(), // Blätterkleid hell
        'G' to 0xFF3FA86A.toInt(), // Blätterkleid Schatten
        'w' to 0xFFFFC85A.toInt(), // Flügel hell
        'W' to 0xFFE07A22.toInt(), // Flügel Rand
        'y' to 0xFFFFE9A8.toInt(), // Flügelmuster
    ),
    frames = listOf(
        // Flügel weit geöffnet
        """
        ................................
        ................................
        ..........o..........o..........
        ...........o........o...........
        ............o......o............
        ............oHHHHHHo............
        ...........oHhhhhhhHo...........
        ..........oHhsssssshHo..........
        ..........oHhsesseshHo..........
        ..........oHhsssSsshHo..........
        ...........oHssssssho...........
        ..............oSSo..............
        ........oWwWo.oggo.oWwWo........
        .......oWwwWo.oggo.oWwwWo.......
        ......oWwyywWosGGsoWwyywWo......
        ......oWyyyyWogGGgoWyyyyWo......
        ......oWyyyyWogGGgoWyyyyWo......
        ......oWwyywWogGGgoWwyywWo......
        .......oWwWo.ogGGgo.oWwWo.......
        .........oWo.ogGGgo.oWo.........
        ............ogGGGGgo............
        ............ogGGGGgo............
        ...........ogGGGGGGgo...........
        ..........ogGGGGGGGGgo..........
        .............oso.oso............
        .............oso.oso............
        .............oSo.oSo............
        ................................
        ................................
        ................................
        ................................
        ................................
        """.spriteRows(),

        // Flügel angelegt — der Schlag
        """
        ................................
        ................................
        ..........o..........o..........
        ...........o........o...........
        ............o......o............
        ............oHHHHHHo............
        ...........oHhhhhhhHo...........
        ..........oHhsssssshHo..........
        ..........oHhsesseshHo..........
        ..........oHhsssSsshHo..........
        ...........oHssssssho...........
        ..............oSSo..............
        ..........oWo.oggo.oWo..........
        .........oWwo.oggo.oWwo.........
        ........oWwwWosGGsoWwwWo........
        ........oWyyWogGGgoWyyWo........
        ........oWyyWogGGgoWyyWo........
        ........oWwwWogGGgoWwwWo........
        ........oWwWoogGGgooWwWo........
        .........oWo.ogGGgo.oWo.........
        ............ogGGGGgo............
        ............ogGGGGgo............
        ...........ogGGGGGGgo...........
        ..........ogGGGGGGGGgo..........
        .............oso.oso............
        .............oso.oso............
        .............oSo.oSo............
        ................................
        ................................
        ................................
        ................................
        ................................
        """.spriteRows(),
    ),
    frameMillis = 260,
)
